/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as GithubRouteImport } from './routes/github'
import { Route as ImpactRouteImport } from './routes/impact'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as PassportRouteImport } from './routes/passport'
import { Route as PersonasRouteImport } from './routes/personas'
import { Route as RecruiterRouteImport } from './routes/recruiter'
import { Route as ReevaluateRouteImport } from './routes/reevaluate'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as PPassportNumberRouteImport } from './routes/p.$passportNumber'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const GithubRoute = GithubRouteImport.update({
  id: '/github',
  path: '/github',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactRoute = ImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const PassportRoute = PassportRouteImport.update({
  id: '/passport',
  path: '/passport',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonasRoute = PersonasRouteImport.update({
  id: '/personas',
  path: '/personas',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruiterRoute = RecruiterRouteImport.update({
  id: '/recruiter',
  path: '/recruiter',
  getParentRoute: () => rootRouteImport,
} as any)
const ReevaluateRoute = ReevaluateRouteImport.update({
  id: '/reevaluate',
  path: '/reevaluate',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const PPassportNumberRoute = PPassportNumberRouteImport.update({
  id: '/p/$passportNumber',
  path: '/p/$passportNumber',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/audit': typeof AuditRoute
  '/auth': typeof AuthRoute
  '/compare': typeof CompareRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/github': typeof GithubRoute
  '/impact': typeof ImpactRoute
  '/jobs': typeof JobsRoute
  '/passport': typeof PassportRoute
  '/personas': typeof PersonasRoute
  '/recruiter': typeof RecruiterRoute
  '/reevaluate': typeof ReevaluateRoute
  '/review': typeof ReviewRoute
  '/roadmap': typeof RoadmapRoute
  '/skills': typeof SkillsRoute
  '/upload': typeof UploadRoute
  '/p/$passportNumber': typeof PPassportNumberRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/audit': typeof AuditRoute
  '/auth': typeof AuthRoute
  '/compare': typeof CompareRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/github': typeof GithubRoute
  '/impact': typeof ImpactRoute
  '/jobs': typeof JobsRoute
  '/passport': typeof PassportRoute
  '/personas': typeof PersonasRoute
  '/recruiter': typeof RecruiterRoute
  '/reevaluate': typeof ReevaluateRoute
  '/review': typeof ReviewRoute
  '/roadmap': typeof RoadmapRoute
  '/skills': typeof SkillsRoute
  '/upload': typeof UploadRoute
  '/p/$passportNumber': typeof PPassportNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/audit': typeof AuditRoute
  '/auth': typeof AuthRoute
  '/compare': typeof CompareRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/github': typeof GithubRoute
  '/impact': typeof ImpactRoute
  '/jobs': typeof JobsRoute
  '/passport': typeof PassportRoute
  '/personas': typeof PersonasRoute
  '/recruiter': typeof RecruiterRoute
  '/reevaluate': typeof ReevaluateRoute
  '/review': typeof ReviewRoute
  '/roadmap': typeof RoadmapRoute
  '/skills': typeof SkillsRoute
  '/upload': typeof UploadRoute
  '/p/$passportNumber': typeof PPassportNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assistant'
    | '/audit'
    | '/auth'
    | '/compare'
    | '/dashboard'
    | '/documents'
    | '/github'
    | '/impact'
    | '/jobs'
    | '/passport'
    | '/personas'
    | '/recruiter'
    | '/reevaluate'
    | '/review'
    | '/roadmap'
    | '/skills'
    | '/upload'
    | '/p/$passportNumber'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assistant'
    | '/audit'
    | '/auth'
    | '/compare'
    | '/dashboard'
    | '/documents'
    | '/github'
    | '/impact'
    | '/jobs'
    | '/passport'
    | '/personas'
    | '/recruiter'
    | '/reevaluate'
    | '/review'
    | '/roadmap'
    | '/skills'
    | '/upload'
    | '/p/$passportNumber'
  id:
    | '__root__'
    | '/'
    | '/assistant'
    | '/audit'
    | '/auth'
    | '/compare'
    | '/dashboard'
    | '/documents'
    | '/github'
    | '/impact'
    | '/jobs'
    | '/passport'
    | '/personas'
    | '/recruiter'
    | '/reevaluate'
    | '/review'
    | '/roadmap'
    | '/skills'
    | '/upload'
    | '/p/$passportNumber'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssistantRoute: typeof AssistantRoute
  AuditRoute: typeof AuditRoute
  AuthRoute: typeof AuthRoute
  CompareRoute: typeof CompareRoute
  DashboardRoute: typeof DashboardRoute
  DocumentsRoute: typeof DocumentsRoute
  GithubRoute: typeof GithubRoute
  ImpactRoute: typeof ImpactRoute
  JobsRoute: typeof JobsRoute
  PassportRoute: typeof PassportRoute
  PersonasRoute: typeof PersonasRoute
  RecruiterRoute: typeof RecruiterRoute
  ReevaluateRoute: typeof ReevaluateRoute
  ReviewRoute: typeof ReviewRoute
  RoadmapRoute: typeof RoadmapRoute
  SkillsRoute: typeof SkillsRoute
  UploadRoute: typeof UploadRoute
  PPassportNumberRoute: typeof PPassportNumberRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/github': {
      id: '/github'
      path: '/github'
      fullPath: '/github'
      preLoaderRoute: typeof GithubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact': {
      id: '/impact'
      path: '/impact'
      fullPath: '/impact'
      preLoaderRoute: typeof ImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passport': {
      id: '/passport'
      path: '/passport'
      fullPath: '/passport'
      preLoaderRoute: typeof PassportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personas': {
      id: '/personas'
      path: '/personas'
      fullPath: '/personas'
      preLoaderRoute: typeof PersonasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiter': {
      id: '/recruiter'
      path: '/recruiter'
      fullPath: '/recruiter'
      preLoaderRoute: typeof RecruiterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reevaluate': {
      id: '/reevaluate'
      path: '/reevaluate'
      fullPath: '/reevaluate'
      preLoaderRoute: typeof ReevaluateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$passportNumber': {
      id: '/p/$passportNumber'
      path: '/p/$passportNumber'
      fullPath: '/p/$passportNumber'
      preLoaderRoute: typeof PPassportNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssistantRoute: AssistantRoute,
  AuditRoute: AuditRoute,
  AuthRoute: AuthRoute,
  CompareRoute: CompareRoute,
  DashboardRoute: DashboardRoute,
  DocumentsRoute: DocumentsRoute,
  GithubRoute: GithubRoute,
  ImpactRoute: ImpactRoute,
  JobsRoute: JobsRoute,
  PassportRoute: PassportRoute,
  PersonasRoute: PersonasRoute,
  RecruiterRoute: RecruiterRoute,
  ReevaluateRoute: ReevaluateRoute,
  ReviewRoute: ReviewRoute,
  RoadmapRoute: RoadmapRoute,
  SkillsRoute: SkillsRoute,
  UploadRoute: UploadRoute,
  PPassportNumberRoute: PPassportNumberRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
